def simple_seq():
    # croc = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACACACAAAAACGACGACGACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    base = "TTTTTTTTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACACACACACAAAAACGACGACGACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
    return base

def seq_high_entrophy():
    # croc = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACACACAAAAACGACGACGACGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    base = "CCACGAAGCGTCCCGCCCAGGACGCGAGCATGGTCTTGGTTCGAGCCATTCGCGGGTCTGGTCGTACGTCTCCGAGGTTATCCTCGCGCTCCTACCGTTGTTTAACGCCCGATCTTTGCGGTCTGTGTTTGGAGACACAACAATCTTAAGCCACGAAGCGTCCCGCCCAGGACGCGAGCATGGTCTTGGTTCGAGCCATTCGCGGGTCTGGTCGTACGTCTCCGAGGTTATCCTCGCGCTCCTACCGTTGTTTAACGCCCGATCTTTGCGGTCTGTGTTTGGAGACACAACAATCTTAAG"
    return base

def seq_mono_repeat_wone_impurity():
    base = "CCACGAAGCGTCCCGCCCAGGACGC"+"A"*30+"C"+"A"*29+"CCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGC"
    return base

def seq_tri_repeat_full_purity():
    base = "CCACGAAGCGTCCCGCCCAGGACGC"+"ACT"*4+"CCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGCCCACGAAGCGTCCCGCCCAGGACGC"
    return base


def real_seq():
    # seq is overall: 16,520-16,732
    # locus is 16620-16632
    pre_locus = "TTCTGACCACTTAACAAACCCACAGAAAATCCACCCGAGTGCACTGAGCACGCCAGAAATCAGGTGGCCTCAAAGAGCTGCTCCCACCTGAAGGAGACGC"
    locus = "GCTGCTGCTGCTG"
    post_locus= "TCGTCCTGCCTGGCGCCTTGGCCTACAGGGGCCGCGGTTGAGGGTGGGAGTGGGGGTGCACTGGCCAGCACCTCAGGAGCTGGGGGTGGTGGTGGGGGCG"
    return pre_locus+locus+post_locus

